### ISSUE TITLE
[UX] Default task activity

### ISSUE THREAD

**Issue by michalpiasecki1** [Code-Poets/sheetstorm#185] opened 2019-05-09 14:04 UTC
on /report/ is a list of task activities with default with "Administrative". As a DevOps I will be mainly using "DevOps" label, and I could use a feature to make it default. Otherwise I need to change it everytime when I add an entry from "Administrative" to "DevOps" which is not time effective

**Comment by Karrp** [comment] 2019-06-06 10:54
duplicate of #203

**Closed by Karrp** 2019-06-06 10:54 UTC
Labels: UX, duplicate, feature
